- src/main/java/uk/gov/hmcts/reform/pip/model/LogBuilder.java
- src/main/java/uk/gov/hmcts/reform/pip/model/enums/UserActions.java
- src/test/java/uk/gov/hmcts/reform/pip/model/LogBuilderTest.java
added a log writer to follow a predefined format for how our logs are expected to look
```
[ ] Yes
[x] No
```
> Log writer

- build.gradle
**Before creating a pull request make sure that:**
Please remove this line and everything above and fill the following sections:
```
[ ] Yes
[ ] No
```
> added version number to dependency

- build.gradle
- src/main/java/uk/gov/hmcts/reform/pip/model/LogBuilder.java
- src/main/java/uk/gov/hmcts/reform/pip/model/enums/UserActions.java
- src/test/java/uk/gov/hmcts/reform/pip/model/LogBuilderTest.java
https://tools.hmcts.net/jira/browse/PUB-1341
Updated for more logging types + extended actions
```
[ ] Yes
[x] No
```
> PUB-1341 - Updated data models library

- build.gradle
- src/main/java/uk/gov/hmcts/reform/pip/model/enums/UserActions.java
https://tools.hmcts.net/jira/browse/PUB-1512
Add user action for updating list type which is required for PUB-1512.
[ ] Yes
[x] No
> PUB-1512 Add user action for updating list type

- build.gradle
N/A
Updated version number to capture dependabot changes
```
[ ] Yes
[x] No
```
> 1.4.2 - Updated version number

- build.gradle
- config/owasp/suppressions.xml
- gradle/wrapper/gradle-wrapper.properties
https://tools.hmcts.net/jira/browse/PUB-1910
Updated dependencies + suppressions
```
[ ] Yes
[x] No
```
> PUB-1910 - Updated dependencies + suppressions

- build.gradle
https://tools.hmcts.net/jira/browse/PUB-1996
```
[ ] Yes
[x] No
```
> PUB-1996 - Dependency updates

- build.gradle
- src/main/java/uk/gov/hmcts/reform/pip/model/subscription/Subscription.java
https://tools.hmcts.net/jira/browse/PUB-2002
Added party names to the subscriptions model.
```
[ ] Yes
[x] No
```
> PUB-2002 - Added party names

- build.gradle
https://tools.hmcts.net/jira/browse/PUB-1996
Updated dependencies
```
[ ] Yes
[x] No
```
> PUB-1996 - Updated dependencies

- build.gradle
- src/main/java/uk/gov/hmcts/reform/pip/model/publication/FileType.java
https://tools.hmcts.net/jira/browse/PUB-1960
Add file extension to file type enum
```
[ ] Yes
[x] No
```
> PUB-1960 Add file extension to file type enum

- build.gradle
- config/checkstyle/checkstyle.xml
- config/owasp/suppressions.xml
- config/pmd/ruleset.xml
- src/main/java/uk/gov/hmcts/reform/pip/model/account/PiUser.java
- src/main/java/uk/gov/hmcts/reform/pip/model/location/Location.java
- src/main/java/uk/gov/hmcts/reform/pip/model/subscription/LocationSubscriptionDeletion.java
- src/main/java/uk/gov/hmcts/reform/pip/model/subscription/Subscription.java
- src/main/java/uk/gov/hmcts/reform/pip/model/subscription/ThirdPartySubscription.java
- src/main/java/uk/gov/hmcts/reform/pip/model/subscription/ThirdPartySubscriptionArtefact.java
https://tools.hmcts.net/jira/browse/PUB-1687
- Update springboot version to V3
- Updated checkstyles version + file
- Updated PMD + fixed deprecated property
- Removed unneeded dependency management section
- Excluded commons logging
```
[ ] Yes
[x] No
```
> PUB-1687 - Update Springboot to V3

- build.gradle
- src/main/java/uk/gov/hmcts/reform/pip/model/publication/ListType.java
- src/main/java/uk/gov/hmcts/reform/pip/model/publication/helpers/ListTypeHelper.java
- src/test/java/uk/gov/hmcts/reform/pip/model/publication/ListTypeTest.java
https://tools.hmcts.net/jira/browse/PUB-1974
Add list type friendly name
```
[ ] Yes
[x] No
```
> PUB-1974 Add list type friendly name

- build.gradle
N/A
Updated spring version to fix CVE
```
[ ] Yes
[x] No
```
> Fixed spring version

- build.gradle
- src/main/java/uk/gov/hmcts/reform/pip/model/publication/ListType.java
https://tools.hmcts.net/jira/browse/PUB-1711
Add new list type flag for additional PDF
```
[ ] Yes
[x] No
```
> PUB-1711 Add new list type flag for additional PDF

- build.gradle
- src/main/java/uk/gov/hmcts/reform/pip/model/authentication/roles/IsB2C.java
https://tools.hmcts.net/jira/browse/PUB-2193
Add B2C authentication role
```
[ ] Yes
[x] No
```
> PUB-2193 Add B2C authentication role

- .github/workflows/ci.yml
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- gradlew
https://tools.hmcts.net/jira/browse/PUB-2265
Monthly dependency updates
```
[ ] Yes
[x] No
```
> PUB-2265 - Updated dependencies

- README.md
Merge code freeze branch to Master
```
[ ] Yes
[x] No
```
> Merge code freeze branch to Master

- Jenkinsfile_nightly
https://tools.hmcts.net/jira/browse/PUB-1619
Fix nightly build
```
[ ] Yes
[x] No
```
> PUB-1619 - Enable nightly

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- gradlew
https://tools.hmcts.net/jira/browse/PUB-2293
```
[ ] Yes
[x] No
```
> PUB-2293 - Dependency updates

- build.gradle
- src/main/java/uk/gov/hmcts/reform/pip/model/publication/Artefact.java
https://tools.hmcts.net/jira/browse/PUB-2121
Add payload size to artefact metadata
```
[ ] Yes
[x] No
```
> PUB-2121 Add payload size to artefact metadata

- build.gradle
https://tools.hmcts.net/jira/browse/PUB-2334
```
[ ] Yes
[x] No
```
> PUB -2334 Dependency updates

- build.gradle
https://tools.hmcts.net/jira/browse/PUB-2447
```
[ ] Yes
[x] No
```
> PUB-2447 - Dependency updates

- build.gradle
https://tools.hmcts.net/jira/browse/PUB-2461
Upgrading to Java 21
```
[ ] Yes
[x] No
```
> PUB-2461: Upgrading to Java 21

- .github/workflows/ci.yml
- .github/workflows/jitpack_build.yml
- build.gradle
https://tools.hmcts.net/jira/browse/PUB-2461
Fix CI + Jitpack
```
[ ] Yes
[x] No
```
> Fix jitpack

- jitpack.yml
https://tools.hmcts.net/jira/browse/PUB-2461
Fix jitpack
```
[ ] Yes
[x] No
```
> Fixed jitpack

- Jenkinsfile_nightly
https://tools.hmcts.net/jira/browse/PUB-2490
Updated nightly build time
```
[ ] Yes
[x] No
```
> PUB-2490 - Updated nightly time

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- gradlew
https://tools.hmcts.net/jira/browse/PUB-2511
Updating dependencies
```
[ ] Yes
[x] No
```
> PUB-2511: Updating dependencies

- build.gradle
- config/pmd/ruleset.xml
https://tools.hmcts.net/jira/browse/PUB-2650
Updated dependencies
```
[ ] Yes
[x] No
```
> PUB-2650 - Updated build gradle

- build.gradle
- src/main/java/uk/gov/hmcts/reform/pip/model/report/AccountMiData.java
- src/main/java/uk/gov/hmcts/reform/pip/model/report/AllSubscriptionMiData.java
- src/main/java/uk/gov/hmcts/reform/pip/model/report/LocalSubscriptionMiData.java
- src/main/java/uk/gov/hmcts/reform/pip/model/report/PublicationMiData.java
https://tools.hmcts.net/jira/browse/PUB-2249
Add models for MI reporting endpoints
```
[ ] Yes
[x] No
```
> PUB-2249 - Add models for MI reporting

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
https://tools.hmcts.net/jira/browse/PUB-2693
Updated dependencies
```
[ ] Yes
[x] No
```
> PUB-2693 - Updated dependencies

- build.gradle
https://tools.hmcts.net/jira/browse/PUB-2693
Updated version
```
[ ] Yes
[x] No
```
> PUB-2693 - Updated version

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- gradlew
https://tools.hmcts.net/jira/browse/PUB-2758
Monthly dependency update
```
[ ] Yes
[x] No
```
> PUB-2758 Monthly dependency update

- build.gradle
https://tools.hmcts.net/jira/browse/PUB-2758
Updated spring
```
[ ] Yes
[x] No
```
> PUB-2758 - Updated build.gradle

- build.gradle
https://tools.hmcts.net/jira/browse/PUB-2758
Updated version number
```
[ ] Yes
[x] No
```
> Updated version number

- build.gradle
N/A
Updating version
```
[ ] Yes
[x] No
```
> Updated version

- build.gradle
- src/main/java/uk/gov/hmcts/reform/pip/model/publication/ListType.java
- src/main/java/uk/gov/hmcts/reform/pip/model/publication/helpers/ListTypeHelper.java
https://tools.hmcts.net/jira/browse/PUB-2739
Add Asylum Support Tribunal Daily Hearing List
```
[ ] Yes
[x] No
```
> PUB-2739 Add Asylum Support Tribunal Daily Hearing List

- build.gradle
N/A
Update version of fortify to fix build
```
[ ] Yes
[x] No
```
> Updated version of fortify client

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
https://tools.hmcts.net/jira/browse/PUB-2791
Monthly dependency update
```
[ ] Yes
[x] No
```
> PUB-2791 - Monthly dependency update

- build.gradle
fix build number
[ ] Yes
[x] No
> fix build number

- build.gradle
https://tools.hmcts.net/jira/browse/PUB-2864
Update version number
[ ] Yes
[x] No
> Update Version Number

- src/main/java/uk/gov/hmcts/reform/pip/model/publication/ListType.java
https://tools.hmcts.net/jira/browse/PUB-2918
Removed planning court daily cause list
```
[ ] Yes
[x] No
```
> PUB-2918 - Removed planning court

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
https://tools.hmcts.net/jira/browse/PUB-2959
```
[ ] Yes
[x] No
```
> PUB-2959 - Dependency updates

- src/main/java/uk/gov/hmcts/reform/pip/model/publication/ListType.java
https://tools.hmcts.net/jira/browse/PUB-2961
Updated list type
```
[ ] Yes
[x] No
```
> PUB-2961 - Updated mags public list type

- src/main/java/uk/gov/hmcts/reform/pip/model/publication/ListType.java
https://tools.hmcts.net/jira/browse/PUB-2984
Add new list type for Magistrates Public Adult Court List
```
[ ] Yes
[x] No
```
> PUB-2984 Add new list type for Magistrates Public Adult Court List

- build.gradle
- src/main/java/uk/gov/hmcts/reform/pip/model/publication/ListType.java
- src/test/java/uk/gov/hmcts/reform/pip/model/publication/ListTypeTest.java
https://tools.hmcts.net/jira/browse/PUB-2965
Refactored list type + added deprecated flag
```
[ ] Yes
[x] No
```
> PUB-2965 - Refactored list type + added deprecation flag

- src/main/java/uk/gov/hmcts/reform/pip/model/publication/ArtefactType.java
https://tools.hmcts.net/jira/browse/PUB-2844
Add new ArtefactType
[ ] Yes
[x] No
> PUB- 2844 Upload Html to AWS S3 Bucket
